### ISSUE TITLE
Confusión en el nombre del plugin

### ISSUE THREAD

**Issue by ricrogz** [felexx90/service.subtitles.subswiki#1]
Hola! Por casualidad he dado con tu addon... y no funciona, Kodi lo rechaza al intentar instalarlo.

Lo he estado mirando, y se debe a que mientras tu proyecto se llama "service.subtitles.subswiki", en el fichero "addon.xml" tienes varias referencias a "subwiki" (sin la "s" después de "sub"), y no funciona. En cuanto se cambian todos a "subswiki" la cosa mejora.

Por otro lado, según esto http://kodi.wiki/view/Add-on_structure#icon.png, tu icono no es reglamentario: no tiene dimensiones de 256x256 (aunque la página debe estar anticuada, porque ni siquiera menciona el "logo.png", y en su lugar sí menciona el "fanart.png", aunque esto lo digo desde el desconocimiento, no estoy muy puesto en addons de Kodi).

Y ya puestos, como sugerencia, yo me llevaría todas las funciones auxiliares a un paquete dentro de un directorio "resources/lib" (dejando en "service.py" sólo aquello a lo que llame Kodi directamente). Esto te permitiría desarrollar el códig desde cualquier editor y probar el código desde la consola, sin tener que cargar los paquetes "xbmc" de Kodi.

**Comment by shadowazxerpt** [comment]
hola en la siguiente linea 12 (- < summary  lang = " en " > Subwiki .com </ summary >
+ < summary  lang = " en " > Subswiki .com </ summary >) tambien faltaba la "s" para que pueda funcional

**Comment by felexx90** [comment]
Muchas gracias por los aportes, inicialmente lo hice como hobby y no lo volví tocar, pero ya he corregido 
la mayoría de esos problemas que mencionan. con respecto a la organización del paquete, resulta que me base en un addon ya creado y así estaba organizado por eso todo esta en el service.py
